#!/bin/bash

# Script to help set up GitHub Secrets
# This script displays the values you need to add to GitHub Secrets

echo "========================================="
echo "GitHub Secrets Configuration"
echo "========================================="
echo ""
echo "Go to: https://github.com/YOUR_USERNAME/YOUR_REPO/settings/secrets/actions"
echo ""
echo "Add the following secrets:"
echo ""
echo "1. VPS_HOST"
echo "   Value: 205.209.121.94"
echo ""
echo "2. VPS_USERNAME"
echo "   Value: root"
echo ""
echo "3. VPS_PORT"
echo "   Value: 22"
echo ""
echo "4. VPS_PASSWORD"
echo "   Value: x93Zoquy&BTJQ0"
echo ""
echo "5. ENV_FILE"
echo "   Value (copy everything below):"
echo "   ---"
cat .env
echo "   ---"
echo ""
echo "========================================="
echo "After adding secrets, commit and push:"
echo "========================================="
echo ""
echo "git add ."
echo "git commit -m 'Add deployment configuration'"
echo "git push origin main"
echo ""
